### ISSUE TITLE
Single Discovery does not work

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/discovery-ui#30]
I tried putting http://linked.opendata.cz/ldcp/resource/ldvm/experiment/3/config in Discovery input IRI and  clicking Discover. Ended up with errors in console and blank screen.

The same happens when I copy the contents to the input field

**Comment by jirihelmich** [comment]
Hint: Discovery start is not called.

**Comment by jirihelmich** [comment]
Fixed the UI bug. The IRI is no longer valid, tried with https://discovery.linkedpipes.com/resource/experiment/2/config which finds 0 pipelines, is that correct?

**Comment by jirihelmich** [comment]
Disregard, working fully with https://discovery.linkedpipes.com/resource/discovery/3/config.
