### ISSUE TITLE
"Run pipeline" runs the pipeline, but gets stuck

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/discovery-ui#34]
When I click "Run" on a discovered pipeline, it gets run in LP-ETL, but nothing happens in the UI. Once I got a 500 error, once it just stopped asking for pipeline execution status, either way, it did not allow me to pass the data to the vizualization app.

**Comment by jirihelmich** [comment]
Finally an issue that forces me to have a look at error handling.
