### ISSUE TITLE
Save experiment data

### ISSUE THREAD

**Issue by jirihelmich** [linkedpipes/discovery-ui#8]
- [ ] input
- [ ] output
- [ ] ETL pipeline id

**Comment by jakubklimek** [comment]
- [ ] ETL pipeline (not only id) - is this the same as output?
- [ ] result: empty data, non-empty data - is this included in output?

**Comment by jirihelmich** [comment]
Output is the grouping of discovered pipelines. ETL pipeline ID is an optional property for each of the groups.

Empty/non-empty is then another additional thing to save.

**Comment by jirihelmich** [comment]
Duplicates #13
